import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to Hospital Applicaiton</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h3>Greetings,</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero, fuga. Vero perferendis et rerum quidem totam cumque quaerat tempore odio delectus? Quo architecto voluptates in eum obcaecati, voluptas deleniti. Deleniti.</p>
        </div>
      </main>
    </div>
  )
}
